#!/bin/bash

script=login.txt

username=$1
password=$2
website=https://alcasar.laplateforme.io/status.php

echo 'key <tab>' >> $script
echo 'key <tab>' >> $script

echo 'key ^J' >> $script
echo 'key ^J' >> $script


for i in `echo $username|fold -w1`
do
   echo 'key '$i >> $script
done

echo 'key <tab>' >> $script

for i in `echo $password|fold -w1` #
do
    echo 'key '$i >> $script
done

echo 'key <tab>' >> $script
echo 'key ^J' >> $script

echo 'key <tab>' >> $script
echo 'key <tab>' >> $script
echo 'key <tab>' >> $script

echo 'key Q' >> $script
echo 'key y' >> $script

lynx $website -accept_all_cookies -cmd_script=login.txt

