#!/bin/bash

script=login.txt

username=$1
password=$2
website=https://alcasar.laplateforme.io/status.php

chall=$(curl -i https://alcasar.laplateforme.io/intercept.php -L  | grep -o -P '(?<=challenge=).*(?=&called)')
curl -H "Content-Type: multipart/form-data" -X POST -F challenge=$chall -F username=$username -F password=$password -F button=Authentication https://alcasar.laplateforme.io/intercept.php -L
